#############################################################################
# Makefile for building: Text_Game
# Generated by qmake (3.1) (Qt 5.9.0)
# Project:  ..\Text_Game\Text_Game.pro
# Template: app
# Command: "C:\Program Files\Qt\5.9\msvc2015_64\bin\qmake.exe" -o Makefile ..\Text_Game\Text_Game.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug"
#############################################################################

MAKEFILE      = Makefile

first: debug
install: debug-install
uninstall: debug-uninstall
QMAKE         = "C:\Program Files\Qt\5.9\msvc2015_64\bin\qmake.exe"
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL_FILE = "C:\Program Files\Qt\5.9\msvc2015_64\bin\qmake.exe" -install qinstall file
QINSTALL_PROGRAM = "C:\Program Files\Qt\5.9\msvc2015_64\bin\qmake.exe" -install qinstall program
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		debug \
		release


debug: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug uninstall
release: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release uninstall

Makefile: ..\Text_Game\Text_Game.pro "..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\win32-msvc\qmake.conf" "..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\features\spec_pre.prf" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\common\windows-gles.conf" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\common\msvc-desktop.conf" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\qconfig.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_3danimation.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_3danimation_private.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_3dcore.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_3dcore_private.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_3dextras.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_3dextras_private.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_3dinput.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_3dinput_private.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_3dlogic.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_3dlogic_private.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_3dquick.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_3dquick_private.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_3dquickanimation.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_3dquickanimation_private.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_3dquickextras.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_3dquickextras_private.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_3dquickinput.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_3dquickinput_private.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_3dquickrender.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_3dquickrender_private.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_3dquickscene2d.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_3dquickscene2d_private.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_3drender.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_3drender_private.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_accessibility_support_private.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_axbase.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_axbase_private.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_axcontainer.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_axcontainer_private.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_axserver.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_axserver_private.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_bluetooth.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_bluetooth_private.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_bootstrap_private.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_concurrent.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_concurrent_private.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_core.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_core_private.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_dbus.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_dbus_private.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_designer.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_designer_private.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_designercomponents_private.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_devicediscovery_support_private.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_egl_support_private.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_eventdispatcher_support_private.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_fb_support_private.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_fontdatabase_support_private.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_gamepad.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_gamepad_private.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_gui.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_gui_private.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_help.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_help_private.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_location.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_location_private.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_multimedia.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_multimedia_private.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_multimediawidgets.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_multimediawidgets_private.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_network.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_network_private.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_nfc.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_nfc_private.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_opengl.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_opengl_private.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_openglextensions.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_openglextensions_private.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_packetprotocol_private.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_platformcompositor_support_private.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_positioning.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_positioning_private.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_printsupport.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_printsupport_private.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_qml.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_qml_private.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_qmldebug_private.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_qmldevtools_private.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_qmltest.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_qmltest_private.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_quick.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_quick_private.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_quickcontrols2.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_quickcontrols2_private.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_quickparticles_private.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_quicktemplates2_private.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_quickwidgets.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_quickwidgets_private.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_scxml.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_scxml_private.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_sensors.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_sensors_private.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_serialbus.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_serialbus_private.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_serialport.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_serialport_private.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_sql.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_sql_private.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_svg.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_svg_private.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_testlib.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_testlib_private.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_theme_support_private.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_uiplugin.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_uitools.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_uitools_private.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_webchannel.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_webchannel_private.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_websockets.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_websockets_private.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_webview.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_webview_private.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_widgets.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_widgets_private.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_winextras.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_winextras_private.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_xml.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_xml_private.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_xmlpatterns.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_xmlpatterns_private.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_zlib_private.pri" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\features\qt_functions.prf" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\features\qt_config.prf" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\win32-msvc\qmake.conf" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\features\spec_post.prf" \
		.qmake.stash \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\features\exclusive_builds.prf" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\common\msvc-version.conf" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\features\toolchain.prf" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\features\default_pre.prf" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\features\win32\default_pre.prf" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\features\resolve_config.prf" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\features\exclusive_builds_post.prf" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\features\default_post.prf" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\features\qml_debug.prf" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\features\precompile_header.prf" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\features\warn_on.prf" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\features\qt.prf" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\features\resources.prf" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\features\moc.prf" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\features\win32\opengl.prf" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\features\uic.prf" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\features\qmake_use.prf" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\features\file_copies.prf" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\features\win32\windows.prf" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\features\testcase_targets.prf" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\features\exceptions.prf" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\features\yacc.prf" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\features\lex.prf" \
		..\Text_Game\Text_Game.pro \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\lib\qtmaind.prl" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\lib\Qt5Widgets.prl" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\lib\Qt5Gui.prl" \
		"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\lib\Qt5Core.prl"
	$(QMAKE) -o Makefile ..\Text_Game\Text_Game.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug"
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\features\spec_pre.prf":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\common\windows-gles.conf":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\common\msvc-desktop.conf":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\qconfig.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_3danimation.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_3danimation_private.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_3dcore.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_3dcore_private.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_3dextras.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_3dextras_private.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_3dinput.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_3dinput_private.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_3dlogic.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_3dlogic_private.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_3dquick.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_3dquick_private.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_3dquickanimation.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_3dquickanimation_private.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_3dquickextras.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_3dquickextras_private.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_3dquickinput.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_3dquickinput_private.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_3dquickrender.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_3dquickrender_private.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_3dquickscene2d.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_3dquickscene2d_private.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_3drender.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_3drender_private.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_accessibility_support_private.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_axbase.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_axbase_private.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_axcontainer.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_axcontainer_private.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_axserver.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_axserver_private.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_bluetooth.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_bluetooth_private.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_bootstrap_private.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_concurrent.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_concurrent_private.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_core.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_core_private.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_dbus.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_dbus_private.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_designer.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_designer_private.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_designercomponents_private.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_devicediscovery_support_private.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_egl_support_private.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_eventdispatcher_support_private.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_fb_support_private.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_fontdatabase_support_private.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_gamepad.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_gamepad_private.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_gui.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_gui_private.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_help.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_help_private.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_location.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_location_private.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_multimedia.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_multimedia_private.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_multimediawidgets.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_multimediawidgets_private.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_network.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_network_private.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_nfc.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_nfc_private.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_opengl.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_opengl_private.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_openglextensions.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_openglextensions_private.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_packetprotocol_private.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_platformcompositor_support_private.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_positioning.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_positioning_private.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_printsupport.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_printsupport_private.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_qml.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_qml_private.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_qmldebug_private.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_qmldevtools_private.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_qmltest.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_qmltest_private.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_quick.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_quick_private.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_quickcontrols2.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_quickcontrols2_private.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_quickparticles_private.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_quicktemplates2_private.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_quickwidgets.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_quickwidgets_private.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_scxml.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_scxml_private.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_sensors.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_sensors_private.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_serialbus.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_serialbus_private.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_serialport.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_serialport_private.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_sql.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_sql_private.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_svg.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_svg_private.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_testlib.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_testlib_private.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_theme_support_private.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_uiplugin.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_uitools.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_uitools_private.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_webchannel.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_webchannel_private.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_websockets.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_websockets_private.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_webview.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_webview_private.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_widgets.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_widgets_private.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_winextras.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_winextras_private.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_xml.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_xml_private.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_xmlpatterns.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_xmlpatterns_private.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\modules\qt_lib_zlib_private.pri":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\features\qt_functions.prf":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\features\qt_config.prf":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\win32-msvc\qmake.conf":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\features\spec_post.prf":
.qmake.stash:
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\features\exclusive_builds.prf":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\common\msvc-version.conf":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\features\toolchain.prf":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\features\default_pre.prf":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\features\win32\default_pre.prf":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\features\resolve_config.prf":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\features\exclusive_builds_post.prf":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\features\default_post.prf":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\features\qml_debug.prf":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\features\precompile_header.prf":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\features\warn_on.prf":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\features\qt.prf":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\features\resources.prf":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\features\moc.prf":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\features\win32\opengl.prf":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\features\uic.prf":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\features\qmake_use.prf":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\features\file_copies.prf":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\features\win32\windows.prf":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\features\testcase_targets.prf":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\features\exceptions.prf":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\features\yacc.prf":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\mkspecs\features\lex.prf":
..\Text_Game\Text_Game.pro:
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\lib\qtmaind.prl":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\lib\Qt5Widgets.prl":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\lib\Qt5Gui.prl":
"..\..\..\..\Program Files\Qt\5.9\msvc2015_64\lib\Qt5Core.prl":
qmake: FORCE
	@$(QMAKE) -o Makefile ..\Text_Game\Text_Game.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug"

qmake_all: FORCE

make_first: debug-make_first release-make_first  FORCE
all: debug-all release-all  FORCE
clean: debug-clean release-clean  FORCE
	-$(DEL_FILE) Text_Game.exp
	-$(DEL_FILE) Text_Game.vc.pdb
	-$(DEL_FILE) Text_Game.ilk
	-$(DEL_FILE) Text_Game.idb
distclean: debug-distclean release-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash Text_Game.lib Text_Game.pdb

debug-mocclean:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug mocclean
release-mocclean:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release mocclean
mocclean: debug-mocclean release-mocclean

debug-mocables:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug mocables
release-mocables:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release mocables
mocables: debug-mocables release-mocables

check: first

benchmark: first
FORCE:

$(MAKEFILE).Debug: Makefile
$(MAKEFILE).Release: Makefile
